# Generated by Django 2.1 on 2019-06-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='author',
        ),
    ]
