# Generated by Django 2.2 on 2019-06-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='total_views',
        ),
    ]
